# Generated by Django 6.0.1 on 2026-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='recipient_type',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('faculty', 'Faculty')], max_length=10),
        ),
    ]
